import { useState, useEffect } from "react";
import { ArrowRight, CheckCircle, Sparkles, FileText, Brain, Target, TrendingUp, Users, Zap, Shield, BarChart3, Clock, Star, Menu, X, Play, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Link } from "react-router-dom";
import heroBanner from "@/assets/hero-banner.jpg";

export default function Landing() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const stats = [
    { value: "70%", label: "Time Saved", icon: Clock },
    { value: "3x", label: "Win Rate Increase", icon: TrendingUp },
    { value: "500+", label: "Active Users", icon: Users },
    { value: "98%", label: "Accuracy Rate", icon: Shield },
  ];

  const features = [
    {
      icon: Brain,
      title: "AI-Powered RFP Analysis",
      description: "Automatically extract key insights, requirements, and challenges from any RFP document with advanced AI.",
      color: "from-blue-500/20 to-purple-500/20",
    },
    {
      icon: Target,
      title: "Smart Discovery Questions",
      description: "Generate tailored questionnaires to understand client needs and pain points intelligently.",
      color: "from-purple-500/20 to-pink-500/20",
    },
    {
      icon: FileText,
      title: "Dynamic Proposal Builder",
      description: "Create winning proposals with AI-suggested content and case studies that resonate.",
      color: "from-pink-500/20 to-red-500/20",
    },
    {
      icon: TrendingUp,
      title: "Value Proposition Generation",
      description: "Craft compelling value propositions aligned with client business objectives automatically.",
      color: "from-green-500/20 to-blue-500/20",
    },
    {
      icon: Zap,
      title: "Real-time Collaboration",
      description: "Work seamlessly with your team on proposals with live updates and version control.",
      color: "from-yellow-500/20 to-orange-500/20",
    },
    {
      icon: BarChart3,
      title: "Analytics & Insights",
      description: "Track proposal performance and get actionable insights to improve your win rate.",
      color: "from-indigo-500/20 to-purple-500/20",
    },
  ];

  const testimonials = [
    {
      quote: "NovaIntel reduced our proposal creation time by 70%. The AI insights are incredibly accurate and have transformed how we approach RFPs.",
      author: "Sarah Chen",
      role: "VP of Sales, TechCorp",
      rating: 5,
    },
    {
      quote: "The discovery questions generated by NovaIntel helped us win deals we thought were lost. It's like having an expert presales consultant 24/7.",
      author: "Michael Rodriguez",
      role: "Presales Director, CloudSolutions",
      rating: 5,
    },
    {
      quote: "The value proposition generator is a game-changer. We've seen a 3x increase in our win rate since implementing NovaIntel.",
      author: "Emily Watson",
      role: "Chief Revenue Officer, DataFlow Inc",
      rating: 5,
    },
  ];

  const benefits = [
    "No credit card required",
    "14-day free trial",
    "Cancel anytime",
    "24/7 support included",
  ];

  return (
    <div className="min-h-screen bg-gradient-hero relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-0 -left-4 w-96 h-96 bg-primary/10 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute top-1/2 -right-4 w-96 h-96 bg-accent/10 rounded-full blur-3xl animate-pulse-slow" style={{ animationDelay: '1s' }}></div>
        <div className="absolute bottom-0 left-1/2 w-96 h-96 bg-primary/5 rounded-full blur-3xl animate-pulse-slow" style={{ animationDelay: '2s' }}></div>
      </div>

      {/* Navigation */}
      <nav className={`sticky top-0 z-50 border-b border-border/40 glass-effect shadow-sm transition-all duration-300 ${scrollY > 50 ? 'bg-background/95 backdrop-blur-md' : 'bg-background/80'}`}>
        <div className="mx-auto flex h-16 max-w-[1388px] items-center justify-between px-4 sm:px-6">
          <Link to="/" className="flex items-center gap-2 sm:gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-primary shadow-md hover:scale-110 transition-transform">
              <span className="text-lg font-bold text-primary-foreground">N</span>
            </div>
            <span className="font-heading text-lg sm:text-xl font-bold">
              Nova<span className="text-primary">Intel</span>
            </span>
          </Link>
          <div className="hidden md:flex items-center gap-6">
            <a href="#features" className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Features</a>
            <a href="#testimonials" className="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Testimonials</a>
            <Link to="/login">
              <Button variant="ghost">Login</Button>
            </Link>
            <Link to="/register">
              <Button variant="gradient" size="sm">Get Started</Button>
            </Link>
          </div>
          <div className="md:hidden">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
            </Button>
          </div>
        </div>
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-border/40 bg-background/95 backdrop-blur-md">
            <div className="px-4 py-4 space-y-3">
              <a href="#features" className="block text-sm font-medium text-muted-foreground hover:text-primary transition-colors" onClick={() => setMobileMenuOpen(false)}>Features</a>
              <a href="#testimonials" className="block text-sm font-medium text-muted-foreground hover:text-primary transition-colors" onClick={() => setMobileMenuOpen(false)}>Testimonials</a>
              <Link to="/login" className="block" onClick={() => setMobileMenuOpen(false)}>
                <Button variant="ghost" className="w-full justify-start">Login</Button>
              </Link>
              <Link to="/register" className="block" onClick={() => setMobileMenuOpen(false)}>
                <Button variant="gradient" className="w-full">Get Started</Button>
              </Link>
            </div>
          </div>
        )}
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden py-20 lg:py-32">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:gap-16 items-center">
            <div className="flex flex-col justify-center space-y-8 animate-fade-in">
              <div className="inline-flex items-center gap-2 self-start rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary backdrop-blur-sm hover:scale-105 transition-transform cursor-default">
                <Sparkles className="h-4 w-4 animate-pulse" />
                AI-Powered Presales Intelligence
              </div>
              <h1 className="font-heading text-5xl font-bold leading-tight tracking-tight lg:text-7xl">
                Accelerate Your Presales Process with{" "}
                <span className="bg-gradient-primary bg-clip-text text-transparent animate-gradient">AI</span>
              </h1>
              <p className="text-xl text-muted-foreground leading-relaxed">
                NovaIntel automates RFP analysis, discovery questions, insights generation, case study mapping, and
                proposal creation—saving you time and winning more deals.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link to="/register">
                  <Button size="lg" className="bg-gradient-primary shadow-lg hover:shadow-xl hover:scale-105 transition-all text-base px-8">
                    Get Started Free <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
                <Button size="lg" variant="outline" className="text-base px-8 hover:scale-105 transition-all">
                  <Play className="mr-2 h-4 w-4" />
                  Watch Demo
                </Button>
              </div>
              <div className="flex flex-wrap gap-6 pt-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center gap-2 text-sm text-muted-foreground">
                    <CheckCircle className="h-4 w-4 text-primary" />
                    <span>{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="relative animate-slide-up">
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-primary rounded-2xl blur-2xl opacity-20 animate-pulse"></div>
                <div className="relative overflow-hidden rounded-2xl shadow-2xl border border-primary/20">
                  <img src={heroBanner} alt="NovaIntel Dashboard" className="h-full w-full object-cover" />
                  <div className="absolute inset-0 bg-gradient-to-t from-primary/10 to-transparent"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-gradient-to-b from-transparent to-background/50">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {stats.map((stat, index) => (
              <Card
                key={index}
                className="group relative overflow-hidden border-border/40 bg-card/60 backdrop-blur-sm p-6 text-center hover:scale-105 transition-all duration-300 hover:shadow-lg hover:border-primary/30"
              >
                <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                <div className="relative">
                  <stat.icon className="h-8 w-8 mx-auto mb-3 text-primary group-hover:scale-110 transition-transform" />
                  <div className="text-3xl font-bold mb-1 bg-gradient-primary bg-clip-text text-transparent">{stat.value}</div>
                  <div className="text-sm text-muted-foreground font-medium">{stat.label}</div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 lg:py-32">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="mb-16 text-center">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary mb-4">
              <Zap className="h-4 w-4" />
              Powerful Features
            </div>
            <h2 className="mb-4 font-heading text-4xl lg:text-5xl font-bold">Everything You Need to Win</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Streamline your entire presales workflow from RFP to proposal with AI-powered intelligence
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <Card
                key={index}
                className="group relative overflow-hidden border-border/40 bg-card/80 backdrop-blur-sm transition-all duration-300 hover:-translate-y-2 hover:shadow-xl hover:shadow-primary/10 hover:border-primary/30"
              >
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.color} opacity-0 group-hover:opacity-100 transition-opacity duration-300`}></div>
                <div className="relative p-8">
                  <div className="mb-6 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-primary/10 to-primary/5 text-primary transition-all duration-300 group-hover:scale-110 group-hover:rotate-3 group-hover:bg-primary group-hover:text-primary-foreground group-hover:shadow-lg">
                    <feature.icon className="h-7 w-7" />
                  </div>
                  <h3 className="mb-3 font-heading text-xl font-bold">{feature.title}</h3>
                  <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
                  <div className="mt-6 flex items-center text-primary opacity-0 group-hover:opacity-100 transition-opacity">
                    <span className="text-sm font-medium">Learn more</span>
                    <ChevronRight className="ml-1 h-4 w-4" />
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 lg:py-32 bg-gradient-to-b from-background to-background/50">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="mb-16 text-center">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary mb-4">
              <Star className="h-4 w-4" />
              Customer Stories
            </div>
            <h2 className="mb-4 font-heading text-4xl lg:text-5xl font-bold">Trusted by Presales Teams</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              See what industry leaders say about NovaIntel
            </p>
          </div>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {testimonials.map((testimonial, index) => (
              <Card
                key={index}
                className="group border-border/40 bg-gradient-card p-8 backdrop-blur-sm transition-all hover:shadow-xl hover:-translate-y-1 hover:border-primary/30"
              >
                <div className="mb-6 flex items-center gap-1 text-accent">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-5 w-5 fill-current" />
                  ))}
                </div>
                <blockquote className="mb-6 text-lg font-medium leading-relaxed">&ldquo;{testimonial.quote}&rdquo;</blockquote>
                <div className="pt-6 border-t border-border/40">
                  <div className="font-semibold text-foreground">{testimonial.author}</div>
                  <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 lg:py-32">
        <div className="mx-auto max-w-[1388px] px-6">
          <Card className="relative overflow-hidden border-border/40 bg-gradient-primary p-12 lg:p-16 text-center text-primary-foreground shadow-2xl">
            <div 
              className="absolute inset-0 opacity-20"
              style={{
                backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
              }}
            ></div>
            <div className="relative z-10">
              <h2 className="mb-4 font-heading text-4xl lg:text-5xl font-bold">Ready to Transform Your Presales?</h2>
              <p className="mb-8 text-lg lg:text-xl opacity-90 max-w-2xl mx-auto">
                Join hundreds of teams already using NovaIntel to win more deals faster. Start your free trial today—no credit card required.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                <Link to="/register">
                  <Button size="lg" variant="secondary" className="shadow-lg hover:scale-105 transition-all text-base px-8">
                    Start Free Trial <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
                <Button size="lg" variant="outline" className="bg-transparent border-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground/10 text-base px-8">
                  Schedule a Demo
                </Button>
              </div>
              <div className="mt-8 flex flex-wrap justify-center gap-6 text-sm opacity-80">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <CheckCircle className="h-4 w-4" />
                    <span>{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/40 bg-background/50 backdrop-blur-sm py-12">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-primary shadow-md">
                  <span className="text-sm font-bold text-primary-foreground">N</span>
                </div>
                <span className="font-heading text-lg font-bold">
                  Nova<span className="text-primary">Intel</span>
                </span>
              </div>
              <p className="text-sm text-muted-foreground">
                AI-powered presales intelligence platform that helps you win more deals faster.
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#features" className="hover:text-primary transition-colors">Features</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Pricing</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Security</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Updates</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-primary transition-colors">About</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Blog</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Careers</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Contact</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Resources</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-primary transition-colors">Documentation</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Support</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">API</a></li>
                <li><a href="#" className="hover:text-primary transition-colors">Community</a></li>
              </ul>
            </div>
          </div>
          <div className="pt-8 border-t border-border/40 flex flex-col sm:flex-row justify-between items-center gap-4">
            <p className="text-sm text-muted-foreground">
              © 2025 NovaIntel. All rights reserved.
            </p>
            <div className="flex gap-6 text-sm text-muted-foreground">
              <a href="#" className="hover:text-primary transition-colors">Privacy</a>
              <a href="#" className="hover:text-primary transition-colors">Terms</a>
              <a href="#" className="hover:text-primary transition-colors">Cookies</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
